[phases.setup]
nixPkgs = ['python312', 'gcc', 'poetry']

[phases.install]
cmds = ['cp README.md /app/README.md', 'poetry install']

[phases.build]
cmd = 'poetry build'

[start]
cmd = "gunicorn -w 4 'main:app' --preload"
