[phases.setup]
nixPkgs = ['python3120', 'gcc', 'poetry']

[build.nixpacksPlan.phases.install]
cmds = ["poetry env use 3.12.0", "poetry install"]

[start]
cmd = "poetry run gunicorn -w 4 'main:app' --preload"
