[phases.setup]
nixPkgs = ['python312', 'gcc', 'poetry']

[phases.install]
cmd = 'python -m venv --copies /opt/venv && . /opt/venv/bin/activate && pip install -r requirements.txt'

[start]
cmd = "poetry run flask --app main run"
