[phases.setup]
nixPkgs = ['...', 'python312', 'gcc', 'poetry']
cmd = "poetry env use 3.12.0"

[build.nixpacksPlan.phases.install]
cmds = ["poetry install"]

[start]
cmd = "poetry run gunicorn -w 4 'main:app' --preload"
